export const references = [
	'Accordion',
	'Alert Dialog',
	'Aspect Ratio',
	'Avatar',
	'Button',
	'Calendar',
	'Checkbox',
	'Collapsible',
	'Combobox',
	'Command',
	'Context Menu',
	'Date Field',
	'Date Picker',
	'Date Range Field',
	'Date Range Picker',
	'Dialog',
	'Dropdown Menu',
	'Label',
	'Link Preview',
	'Menubar',
	'Meter',
	'Navigation Menu',
	'Pagination',
	'PIN Input',
	'Popover',
	'Progress',
	'Radio Group',
	'Range Calendar',
	'Rating Group',
	'Scroll Area',
	'Select',
	'Separator',
	'Slider',
	'Switch',
	'Tabs',
	'Time Field',
	'Time Range Field',
	'Toggle',
	'Toggle Group',
	'Toolbar',
	'Tooltip',
];
